name: pynes-workflow

on:
  push:
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run Flake8
        run: flake8 .

  pytest_check:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: Setup repo
      uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: latest
        python-version: 3.8
        activate-environment: testenv
        channels: conda-forge
    - name: Setup conda python environments
      run: |
        conda config --set always_yes yes --set changeps1 no
        conda install -q -c conda-forge tox
        conda create -q -n py37 python=3.7
        conda create -q -n py38 python=3.8
        conda create -q -n py39 python=3.9
    - name: Run pytest
      env:
        TOXENV: py37,py38,py39
      run: |
        export PY37_PATH=$CONDA/envs/py37/bin
        export PY38_PATH=$CONDA/envs/py38/bin
        export PY39_PATH=$CONDA/envs/py39/bin
        export PATH=$PATH:$PY36_PATH:$PY37_PATH:$PY38_PATH:$PY39_PATH
        tox